---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels: 
    app: environment
  namespace: staging
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: environment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: deploy-pod
      labels:
        app: environment
    spec:
      containers:
        - name: nginx
          image: nginx:1.24.0
          ports:
            - containerPort: 80
    
