---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: environment
  namespace: env
spec:
  type: LoadBalancer
  selector:
    app: environment
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
