---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: jenkins-pod
      labels:
        app: jenkins
    spec:
      containers:
        - name: myjenkins
          image: 806910215750.dkr.ecr.us-east-1.amazonaws.com/syedsohail321:latest
      imagePullSecrets:
        - name: regcred #To pull image from private registry