---
apiVersion: v1
kind: Service
metadata:
  name: service-file-lb
  labels:
    type: service
spec:
  selector:
    app: spc    
  ports:
    - name: spc-svc
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeploy
  labels:
    app: deploy
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: spc
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      name: deploy-spc
      labels:
        app: spc
    spec:
      containers:
        - name: spc
          image: syedsohail321/spcimage:1.0.0
          ports:
            - containerPort: 8080
              protocol: TCP