---
apiVersion: v1
kind: Service
metadata:
  name: service-file-lb
  labels:
    type: service
spec:
  selector:
    app: nginx    
  ports:
    - name: nginx-svc
      port: 80
      targetPort: 80
  type: LoadBalancer